// Bank Soal CBT Remedial - Blok Dasar-Dasar Biomedis FK UHO 2026
// 100 soal: 25 Anatomi, 25 Biokimia, 25 Fisiologi, 25 Histologi
window.QUESTIONS = [
  // ================= ANATOMI (1-25) =================
  {
    no: 1,
    subject: "Anatomi",
    soal: "Seseorang berdiri tegak, wajah menghadap ke depan, kedua lengan di samping tubuh dengan telapak tangan menghadap ke depan. Posisi ini disebut...",
    pilihan: {
      A: "Posisi anatomis",
      B: "Posisi litotomi",
      C: "Posisi supinasi total",
      D: "Posisi fungsional",
      E: "Posisi netral klinis",
    },
    kunci: "A",
    pembahasan: {
      A: "Benar, posisi anatomis adalah posisi acuan standar dalam mendeskripsikan tubuh manusia.",
      B: "Salah, litotomi adalah posisi berbaring dengan panggul dan lutut fleksi, dipakai pada pemeriksaan ginekologi.",
      C: "Salah, supinasi menggambarkan posisi telapak tangan/lengan bawah, bukan istilah posisi tubuh baku.",
      D: "Salah, istilah ini bukan istilah anatomi baku.",
      E: "Salah, tidak dikenal sebagai istilah anatomi baku.",
    },
  },
  {
    no: 2,
    subject: "Anatomi",
    soal: "Bidang yang membagi tubuh menjadi bagian kanan dan kiri yang sama besar disebut bidang...",
    pilihan: {
      A: "Koronal",
      B: "Transversal",
      C: "Sagital median",
      D: "Oblik",
      E: "Horizontal",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, bidang koronal membagi tubuh menjadi depan (anterior) dan belakang (posterior).",
      B: "Salah, bidang transversal membagi tubuh menjadi atas (superior) dan bawah (inferior).",
      C: "Benar, bidang sagital median membagi tubuh tepat di tengah menjadi bagian kanan dan kiri yang sama besar.",
      D: "Salah, bidang oblik adalah potongan miring yang tidak sejajar tiga bidang utama.",
      E: "Salah, horizontal merupakan istilah lain untuk transversal, bukan pembagi kanan-kiri.",
    },
  },
  {
    no: 3,
    subject: "Anatomi",
    soal: "Bidang koronal (frontal) membagi tubuh menjadi bagian...",
    pilihan: {
      A: "Atas dan bawah",
      B: "Kanan dan kiri",
      C: "Depan dan belakang",
      D: "Proksimal dan distal",
      E: "Medial dan lateral",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, itu deskripsi bidang transversal.",
      B: "Salah, itu deskripsi bidang sagital.",
      C: "Benar, bidang koronal membagi tubuh menjadi bagian anterior (depan) dan posterior (belakang).",
      D: "Salah, proksimal-distal adalah istilah arah pada ekstremitas, bukan hasil pembagian bidang.",
      E: "Salah, medial-lateral adalah istilah arah, bukan hasil pembagian bidang koronal.",
    },
  },
  {
    no: 4,
    subject: "Anatomi",
    soal: "Bidang yang membagi tubuh menjadi bagian atas (superior) dan bawah (inferior) adalah bidang...",
    pilihan: {
      A: "Sagital",
      B: "Transversal",
      C: "Koronal",
      D: "Median",
      E: "Longitudinal",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, sagital membagi tubuh kanan-kiri.",
      B: "Benar, bidang transversal (horizontal) memotong tubuh secara melintang menjadi bagian atas dan bawah.",
      C: "Salah, koronal membagi tubuh depan-belakang.",
      D: "Salah, median adalah bidang sagital tepat di tengah tubuh.",
      E: "Salah, longitudinal bukan istilah bidang potong anatomi standar.",
    },
  },
  {
    no: 5,
    subject: "Anatomi",
    soal: "Jantung terletak lebih ke arah kepala dibandingkan diafragma. Hubungan posisi ini digambarkan dengan istilah...",
    pilihan: {
      A: "Jantung inferior terhadap diafragma",
      B: "Jantung superior terhadap diafragma",
      C: "Jantung distal terhadap diafragma",
      D: "Jantung lateral terhadap diafragma",
      E: "Jantung profunda terhadap diafragma",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, inferior berarti lebih ke arah kaki, bertentangan dengan posisi jantung.",
      B: "Benar, superior menunjukkan posisi yang lebih dekat ke arah kepala.",
      C: "Salah, distal dipakai untuk ekstremitas, bukan struktur batang tubuh seperti ini.",
      D: "Salah, lateral berarti menjauhi garis tengah tubuh, bukan menggambarkan arah atas-bawah.",
      E: "Salah, profunda berarti lebih dalam dari permukaan, tidak menggambarkan arah atas-bawah.",
    },
  },
  {
    no: 6,
    subject: "Anatomi",
    soal: "Tulang sternum terletak di bagian depan rongga dada, sedangkan vertebra terletak di bagian belakangnya. Istilah yang tepat menggambarkan posisi sternum terhadap vertebra adalah...",
    pilihan: {
      A: "Sternum posterior terhadap vertebra",
      B: "Sternum ventral (anterior) terhadap vertebra",
      C: "Sternum superior terhadap vertebra",
      D: "Sternum medial terhadap vertebra",
      E: "Sternum distal terhadap vertebra",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, posterior berarti di belakang, justru posisi vertebra.",
      B: "Benar, anterior/ventral berarti ke arah depan tubuh, sesuai posisi sternum.",
      C: "Salah, superior menggambarkan arah atas-bawah, bukan depan-belakang.",
      D: "Salah, medial menggambarkan kedekatan pada garis tengah, bukan depan-belakang.",
      E: "Salah, distal dipakai pada ekstremitas untuk jarak dari pangkal tubuh.",
    },
  },
  {
    no: 7,
    subject: "Anatomi",
    soal: "Ibu jari tangan (digitus I) terletak lebih dekat ke garis tengah tubuh dibanding jari kelingking pada posisi anatomis. Ibu jari disebut berada lebih ke arah...",
    pilihan: {
      A: "Medial",
      B: "Lateral",
      C: "Distal",
      D: "Proksimal",
      E: "Superfisial",
    },
    kunci: "A",
    pembahasan: {
      A: "Benar, medial berarti lebih dekat ke garis tengah tubuh (pada posisi anatomis, telapak tangan menghadap depan sehingga ibu jari berada di sisi medial).",
      B: "Salah, lateral justru berarti menjauhi garis tengah, seperti posisi jari kelingking.",
      C: "Salah, distal-proksimal menggambarkan jarak dari pangkal anggota gerak, bukan dari garis tengah.",
      D: "Salah, sama seperti C, ini bukan istilah untuk kedekatan dengan garis tengah.",
      E: "Salah, superfisial menggambarkan kedekatan dengan permukaan kulit, bukan garis tengah.",
    },
  },
  {
    no: 8,
    subject: "Anatomi",
    soal: "Siku (cubiti) terletak lebih dekat ke bahu dibandingkan pergelangan tangan. Istilah yang tepat menggambarkan posisi siku terhadap pergelangan tangan adalah...",
    pilihan: {
      A: "Distal",
      B: "Proksimal",
      C: "Medial",
      D: "Superior",
      E: "Superfisial",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, distal berarti lebih jauh dari pangkal anggota gerak, justru posisi pergelangan tangan.",
      B: "Benar, proksimal berarti lebih dekat ke pangkal anggota gerak (batang tubuh), sesuai posisi siku.",
      C: "Salah, medial-lateral menggambarkan jarak dari garis tengah tubuh, bukan pangkal ekstremitas.",
      D: "Salah, superior-inferior dipakai untuk arah kepala-kaki pada batang tubuh, kurang tepat untuk hubungan antar-segmen lengan.",
      E: "Salah, superfisial menggambarkan kedalaman dari kulit, bukan jarak dari pangkal.",
    },
  },
  {
    no: 9,
    subject: "Anatomi",
    soal: "Kulit terletak lebih dekat ke permukaan tubuh dibandingkan otot di bawahnya. Kulit dikatakan bersifat...",
    pilihan: {
      A: "Profunda terhadap otot",
      B: "Superfisial terhadap otot",
      C: "Distal terhadap otot",
      D: "Posterior terhadap otot",
      E: "Inferior terhadap otot",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, profunda berarti lebih dalam, justru menggambarkan posisi otot terhadap kulit.",
      B: "Benar, superfisial menggambarkan struktur yang lebih dekat ke permukaan tubuh.",
      C: "Salah, distal dipakai untuk jarak dari pangkal ekstremitas, bukan kedalaman jaringan.",
      D: "Salah, posterior menggambarkan arah belakang tubuh, bukan kedalaman jaringan.",
      E: "Salah, inferior menggambarkan arah bawah tubuh, bukan kedalaman jaringan.",
    },
  },
  {
    no: 10,
    subject: "Anatomi",
    soal: "Gerakan menekuk sendi siku sehingga sudut antar-tulang mengecil disebut...",
    pilihan: {
      A: "Ekstensi",
      B: "Fleksi",
      C: "Abduksi",
      D: "Adduksi",
      E: "Rotasi",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, ekstensi justru gerakan meluruskan sendi sehingga sudut membesar.",
      B: "Benar, fleksi adalah gerakan menekuk sendi yang memperkecil sudut antar-tulang.",
      C: "Salah, abduksi adalah gerakan menjauhkan anggota gerak dari garis tengah tubuh.",
      D: "Salah, adduksi adalah gerakan mendekatkan anggota gerak ke garis tengah tubuh.",
      E: "Salah, rotasi adalah gerakan memutar tulang pada sumbu panjangnya.",
    },
  },
  {
    no: 11,
    subject: "Anatomi",
    soal: "Gerakan mengangkat lengan menjauhi tubuh ke arah samping disebut...",
    pilihan: {
      A: "Adduksi",
      B: "Abduksi",
      C: "Fleksi",
      D: "Sirkumduksi",
      E: "Supinasi",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, adduksi adalah gerakan sebaliknya, mendekatkan lengan ke garis tengah tubuh.",
      B: "Benar, abduksi adalah gerakan menjauhkan anggota gerak dari garis tengah tubuh.",
      C: "Salah, fleksi adalah gerakan menekuk sendi, bukan menjauh dari garis tengah.",
      D: "Salah, sirkumduksi adalah gerakan melingkar gabungan fleksi-ekstensi-abduksi-adduksi.",
      E: "Salah, supinasi menggambarkan posisi telapak tangan menghadap ke atas, bukan gerakan lengan menjauhi tubuh.",
    },
  },
  {
    no: 12,
    subject: "Anatomi",
    soal: "Gerakan memutar lengan bawah sehingga telapak tangan menghadap ke atas disebut...",
    pilihan: {
      A: "Pronasi",
      B: "Supinasi",
      C: "Inversi",
      D: "Eversi",
      E: "Rotasi eksternal",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, pronasi justru memutar telapak tangan menghadap ke bawah.",
      B: "Benar, supinasi adalah gerakan memutar lengan bawah hingga telapak tangan menghadap ke atas.",
      C: "Salah, inversi adalah gerakan telapak kaki menghadap ke medial, bukan gerakan lengan bawah.",
      D: "Salah, eversi adalah gerakan telapak kaki menghadap ke lateral, bukan gerakan lengan bawah.",
      E: "Salah, rotasi eksternal menggambarkan putaran sendi bahu/panggul pada sumbu panjang tulang, istilah berbeda dari pronasi-supinasi.",
    },
  },
  {
    no: 13,
    subject: "Anatomi",
    soal: "Gerakan telapak kaki menghadap ke arah medial (ke dalam) disebut...",
    pilihan: {
      A: "Eversi",
      B: "Inversi",
      C: "Dorsofleksi",
      D: "Plantarfleksi",
      E: "Abduksi kaki",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, eversi justru menghadapkan telapak kaki ke arah lateral (luar).",
      B: "Benar, inversi adalah gerakan telapak kaki menghadap ke medial/dalam.",
      C: "Salah, dorsofleksi adalah gerakan mengangkat punggung kaki ke arah tungkai.",
      D: "Salah, plantarfleksi adalah gerakan menurunkan telapak kaki menjauhi tungkai.",
      E: "Salah, bukan istilah baku untuk gerakan pergelangan kaki ini.",
    },
  },
  {
    no: 14,
    subject: "Anatomi",
    soal: "Jumlah total tulang pada rangka manusia dewasa normal adalah...",
    pilihan: {
      A: "186 tulang",
      B: "196 tulang",
      C: "206 tulang",
      D: "216 tulang",
      E: "226 tulang",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, jumlah ini lebih sedikit dari jumlah sebenarnya.",
      B: "Salah, jumlah ini masih kurang dari jumlah sebenarnya.",
      C: "Benar, rangka manusia dewasa terdiri atas 206 tulang setelah beberapa tulang menyatu sejak masa bayi.",
      D: "Salah, jumlah ini melebihi jumlah sebenarnya.",
      E: "Salah, jumlah ini terlalu banyak dibanding jumlah sebenarnya.",
    },
  },
  {
    no: 15,
    subject: "Anatomi",
    soal: "Femur (tulang paha) termasuk dalam klasifikasi tulang...",
    pilihan: {
      A: "Tulang pipih (flat bone)",
      B: "Tulang pendek (short bone)",
      C: "Tulang panjang (long bone)",
      D: "Tulang tak beraturan (irregular bone)",
      E: "Tulang sesamoid",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, tulang pipih berbentuk lempeng tipis seperti os parietale, bukan seperti femur.",
      B: "Salah, tulang pendek berbentuk hampir sama panjang-lebar-tinggi seperti tulang karpal.",
      C: "Benar, femur memiliki bentuk panjang dengan diafisis dan dua epifisis, ciri khas tulang panjang.",
      D: "Salah, tulang tak beraturan memiliki bentuk kompleks seperti vertebra.",
      E: "Salah, tulang sesamoid tertanam dalam tendon seperti patela, berbeda dari femur.",
    },
  },
  {
    no: 16,
    subject: "Anatomi",
    soal: "Os parietale pada tengkorak termasuk klasifikasi tulang...",
    pilihan: {
      A: "Tulang panjang",
      B: "Tulang pipih",
      C: "Tulang pendek",
      D: "Tulang sesamoid",
      E: "Tulang tak beraturan",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, tulang panjang memiliki diafisis dan epifisis seperti femur, bukan berbentuk lempeng.",
      B: "Benar, os parietale berbentuk lempeng pipih yang melindungi otak, ciri khas tulang pipih.",
      C: "Salah, tulang pendek berbentuk hampir kubus seperti tulang pergelangan tangan.",
      D: "Salah, tulang sesamoid tertanam pada tendon, tidak sesuai dengan os parietale.",
      E: "Salah, tulang tak beraturan memiliki bentuk kompleks seperti tulang wajah tertentu, bukan lempeng pipih.",
    },
  },
  {
    no: 17,
    subject: "Anatomi",
    soal: "Lapisan jaringan ikat yang membungkus permukaan luar tulang, tempat melekatnya tendon dan mengandung pembuluh darah untuk nutrisi tulang, disebut...",
    pilihan: {
      A: "Endosteum",
      B: "Periosteum",
      C: "Perikondrium",
      D: "Epimisium",
      E: "Fasia profunda",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, endosteum melapisi permukaan dalam rongga tulang, bukan permukaan luar.",
      B: "Benar, periosteum adalah selaput jaringan ikat yang membungkus permukaan luar tulang.",
      C: "Salah, perikondrium adalah selaput yang membungkus tulang rawan, bukan tulang keras.",
      D: "Salah, epimisium adalah selaput jaringan ikat yang membungkus seluruh otot rangka.",
      E: "Salah, fasia profunda membungkus otot dan struktur dalam, bukan permukaan tulang secara spesifik.",
    },
  },
  {
    no: 18,
    subject: "Anatomi",
    soal: "Bagian tulang panjang yang berupa batang silindris di tengah disebut...",
    pilihan: {
      A: "Epifisis",
      B: "Diafisis",
      C: "Metafisis",
      D: "Periosteum",
      E: "Kondilus",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, epifisis adalah bagian ujung tulang panjang, bukan bagian tengah.",
      B: "Benar, diafisis adalah batang silindris di bagian tengah tulang panjang.",
      C: "Salah, metafisis adalah zona pertumbuhan antara diafisis dan epifisis.",
      D: "Salah, periosteum adalah selaput pembungkus tulang, bukan bagian struktural batang tulang.",
      E: "Salah, kondilus adalah tonjolan bulat di ujung tulang untuk persendian, bukan bagian tengah.",
    },
  },
  {
    no: 19,
    subject: "Anatomi",
    soal: "Sendi antar tulang tengkorak (sutura) yang hampir tidak dapat bergerak termasuk jenis sendi...",
    pilihan: {
      A: "Diartrosis",
      B: "Amfiartrosis",
      C: "Sinartrosis",
      D: "Sendi sinovial",
      E: "Sendi peluru",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, diartrosis adalah sendi dengan gerak bebas seperti sendi lutut.",
      B: "Salah, amfiartrosis memungkinkan gerak terbatas seperti symphysis pubis.",
      C: "Benar, sinartrosis adalah sendi yang menyatu erat dan hampir tidak bisa bergerak, seperti sutura tengkorak.",
      D: "Salah, sendi sinovial adalah bentuk lain penyebutan diartrosis dengan gerak bebas.",
      E: "Salah, sendi peluru adalah salah satu jenis sendi sinovial dengan gerak sangat luas.",
    },
  },
  {
    no: 20,
    subject: "Anatomi",
    soal: "Symphysis pubis yang menghubungkan kedua tulang panggul dan memungkinkan sedikit pergerakan termasuk jenis sendi...",
    pilihan: {
      A: "Sinartrosis",
      B: "Amfiartrosis",
      C: "Diartrosis",
      D: "Sendi engsel",
      E: "Sendi putar",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, sinartrosis nyaris tidak memiliki pergerakan sama sekali, berbeda dengan symphysis pubis.",
      B: "Benar, amfiartrosis adalah sendi dengan sedikit pergerakan, dihubungkan oleh tulang rawan seperti pada symphysis pubis.",
      C: "Salah, diartrosis memiliki rentang gerak luas, tidak sesuai deskripsi ini.",
      D: "Salah, sendi engsel adalah jenis sendi diartrosis seperti pada siku, bukan symphysis pubis.",
      E: "Salah, sendi putar adalah jenis sendi diartrosis seperti pada leher, bukan symphysis pubis.",
    },
  },
  {
    no: 21,
    subject: "Anatomi",
    soal: "Sendi lutut yang memiliki rongga sendi berisi cairan sinovial dan memungkinkan gerakan luas termasuk jenis sendi...",
    pilihan: {
      A: "Sinartrosis",
      B: "Amfiartrosis",
      C: "Diartrosis (sinovial)",
      D: "Sindesmosis",
      E: "Sinkondrosis",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, sinartrosis hampir tidak dapat bergerak, tidak sesuai sendi lutut.",
      B: "Salah, amfiartrosis hanya memungkinkan gerak terbatas, bukan gerak luas seperti lutut.",
      C: "Benar, diartrosis (sendi sinovial) memiliki rongga berisi cairan sinovial dan memungkinkan gerak luas seperti pada lutut.",
      D: "Salah, sindesmosis adalah sendi fibrosa dengan sedikit gerak, seperti antara tibia-fibula.",
      E: "Salah, sinkondrosis adalah sendi tulang rawan hialin dengan gerak minimal, seperti lempeng pertumbuhan.",
    },
  },
  {
    no: 22,
    subject: "Anatomi",
    soal: "Jenis otot yang bekerja secara volunter (di bawah kesadaran), berinti banyak di tepi, dan menggerakkan rangka tubuh adalah...",
    pilihan: {
      A: "Otot polos",
      B: "Otot jantung",
      C: "Otot rangka",
      D: "Otot viseral",
      E: "Otot involunter",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, otot polos bekerja involunter dan berinti tunggal di tengah sel.",
      B: "Salah, otot jantung bekerja involunter meski memiliki gambaran lurik.",
      C: "Benar, otot rangka bekerja volunter, berinti banyak di tepi sel, dan melekat pada tulang untuk menggerakkan rangka.",
      D: "Salah, otot viseral adalah istilah lain untuk otot polos organ dalam, bersifat involunter.",
      E: "Salah, istilah ini menggambarkan sifat kerja otot secara umum, bukan jenis otot tertentu.",
    },
  },
  {
    no: 23,
    subject: "Anatomi",
    soal: "Otot yang menyusun dinding organ berongga seperti usus, bersifat involunter, dan berinti tunggal di tengah sel disebut otot...",
    pilihan: {
      A: "Rangka",
      B: "Polos",
      C: "Jantung",
      D: "Lurik volunter",
      E: "Skelet",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, otot rangka bersifat volunter dan berinti banyak di tepi.",
      B: "Benar, otot polos bersifat involunter, berinti tunggal di tengah, dan menyusun dinding organ berongga seperti usus.",
      C: "Salah, otot jantung memiliki gambaran lurik dan diskus interkalaris, berbeda dari otot polos.",
      D: "Salah, istilah ini menggambarkan otot rangka, bukan otot polos.",
      E: "Salah, skelet adalah istilah lain untuk otot rangka, bukan otot polos.",
    },
  },
  {
    no: 24,
    subject: "Anatomi",
    soal: "Otot yang hanya ditemukan pada dinding jantung, bersifat involunter, dan memiliki diskus interkalaris adalah otot...",
    pilihan: {
      A: "Polos",
      B: "Rangka",
      C: "Jantung",
      D: "Viseral",
      E: "Skelet",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, otot polos tidak memiliki diskus interkalaris.",
      B: "Salah, otot rangka bersifat volunter, bukan involunter.",
      C: "Benar, otot jantung bersifat involunter, bergambaran lurik, dan memiliki diskus interkalaris penghubung antar sel.",
      D: "Salah, viseral merujuk pada otot polos organ dalam, bukan otot jantung.",
      E: "Salah, skelet merujuk pada otot rangka, bukan otot jantung.",
    },
  },
  {
    no: 25,
    subject: "Anatomi",
    soal: "Tingkatan organisasi tubuh manusia dari yang paling sederhana ke paling kompleks yang benar adalah...",
    pilihan: {
      A: "Organ - jaringan - sel - sistem organ",
      B: "Sel - jaringan - organ - sistem organ",
      C: "Jaringan - sel - organ - sistem organ",
      D: "Sistem organ - organ - jaringan - sel",
      E: "Sel - organ - jaringan - sistem organ",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, urutan ini terbalik antara organ dan jaringan-sel.",
      B: "Benar, organisasi tubuh berjenjang dari sel, membentuk jaringan, jaringan membentuk organ, dan organ membentuk sistem organ.",
      C: "Salah, sel selalu menjadi unit dasar sebelum jaringan terbentuk, bukan sebaliknya.",
      D: "Salah, urutan ini justru dari kompleks ke sederhana, terbalik dari yang diminta.",
      E: "Salah, jaringan seharusnya terbentuk sebelum organ, urutan ini melompati jaringan.",
    },
  },

  // ================= BIOKIMIA (26-50) =================
  {
    no: 26,
    subject: "Biokimia",
    soal: "Unit monomer penyusun karbohidrat kompleks adalah...",
    pilihan: {
      A: "Asam amino",
      B: "Monosakarida",
      C: "Nukleotida",
      D: "Asam lemak",
      E: "Gliserol",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, asam amino adalah monomer protein, bukan karbohidrat.",
      B: "Benar, monosakarida seperti glukosa adalah unit terkecil penyusun karbohidrat.",
      C: "Salah, nukleotida adalah monomer asam nukleat.",
      D: "Salah, asam lemak adalah komponen penyusun lipid, bukan karbohidrat.",
      E: "Salah, gliserol adalah komponen lipid (trigliserida), bukan karbohidrat.",
    },
  },
  {
    no: 27,
    subject: "Biokimia",
    soal: "Ikatan kovalen yang menghubungkan dua molekul monosakarida membentuk disakarida disebut ikatan...",
    pilihan: {
      A: "Peptida",
      B: "Glikosidik",
      C: "Ester",
      D: "Hidrogen",
      E: "Fosfodiester",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, ikatan peptida menghubungkan asam amino pada protein.",
      B: "Benar, ikatan glikosidik terbentuk antara dua monosakarida melalui reaksi kondensasi.",
      C: "Salah, ikatan ester menghubungkan gliserol dengan asam lemak pada lipid.",
      D: "Salah, ikatan hidrogen adalah interaksi lemah, bukan ikatan kovalen antar monosakarida.",
      E: "Salah, ikatan fosfodiester menghubungkan nukleotida pada asam nukleat.",
    },
  },
  {
    no: 28,
    subject: "Biokimia",
    soal: "Sukrosa (gula pasir) tersusun dari kombinasi dua monosakarida, yaitu...",
    pilihan: {
      A: "Glukosa dan galaktosa",
      B: "Glukosa dan fruktosa",
      C: "Fruktosa dan galaktosa",
      D: "Dua molekul glukosa",
      E: "Dua molekul fruktosa",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, kombinasi ini membentuk laktosa, bukan sukrosa.",
      B: "Benar, sukrosa terbentuk dari glukosa + fruktosa → sukrosa + H2O melalui ikatan glikosidik.",
      C: "Salah, kombinasi ini bukan penyusun disakarida umum yang dikenal.",
      D: "Salah, dua molekul glukosa membentuk maltosa, bukan sukrosa.",
      E: "Salah, dua molekul fruktosa bukan kombinasi disakarida yang dikenal.",
    },
  },
  {
    no: 29,
    subject: "Biokimia",
    soal: "Polisakarida yang berfungsi sebagai cadangan energi utama pada sel hewan dan disimpan terutama di hati dan otot adalah...",
    pilihan: {
      A: "Selulosa",
      B: "Amilum (pati)",
      C: "Glikogen",
      D: "Kitin",
      E: "Pektin",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, selulosa adalah komponen struktural dinding sel tumbuhan, bukan cadangan energi hewan.",
      B: "Salah, amilum adalah cadangan energi pada tumbuhan, bukan pada hewan.",
      C: "Benar, glikogen adalah polisakarida cadangan energi utama pada hewan, disimpan di hati dan otot.",
      D: "Salah, kitin adalah komponen struktural eksoskeleton artropoda dan dinding sel fungi.",
      E: "Salah, pektin adalah komponen dinding sel tumbuhan, bukan cadangan energi hewan.",
    },
  },
  {
    no: 30,
    subject: "Biokimia",
    soal: "Selulosa sulit dicerna oleh enzim pencernaan manusia karena tersusun dari glukosa dengan ikatan...",
    pilihan: {
      A: "Alfa 1,4 glikosidik",
      B: "Alfa 1,6 glikosidik",
      C: "Beta 1,4 glikosidik",
      D: "Ikatan peptida",
      E: "Ikatan ester",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, ikatan alfa 1,4 terdapat pada amilum dan glikogen yang dapat dicerna manusia.",
      B: "Salah, ikatan alfa 1,6 adalah titik percabangan pada amilopektin dan glikogen.",
      C: "Benar, selulosa tersusun dari ikatan beta 1,4 glikosidik yang tidak dapat dipecah enzim pencernaan manusia.",
      D: "Salah, ikatan peptida ditemukan pada protein, tidak relevan dengan struktur selulosa.",
      E: "Salah, ikatan ester ditemukan pada lipid, tidak relevan dengan struktur selulosa.",
    },
  },
  {
    no: 31,
    subject: "Biokimia",
    soal: "Unit monomer penyusun protein adalah...",
    pilihan: {
      A: "Monosakarida",
      B: "Nukleotida",
      C: "Asam amino",
      D: "Asam lemak",
      E: "Gliserol",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, monosakarida adalah monomer karbohidrat.",
      B: "Salah, nukleotida adalah monomer asam nukleat.",
      C: "Benar, asam amino adalah unit monomer yang berikatan membentuk rantai protein.",
      D: "Salah, asam lemak adalah komponen penyusun lipid.",
      E: "Salah, gliserol adalah komponen lipid, bukan protein.",
    },
  },
  {
    no: 32,
    subject: "Biokimia",
    soal: "Ikatan kovalen yang menghubungkan gugus karboksil satu asam amino dengan gugus amino asam amino lainnya disebut ikatan...",
    pilihan: {
      A: "Glikosidik",
      B: "Peptida",
      C: "Fosfodiester",
      D: "Hidrogen",
      E: "Disulfida",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, ikatan glikosidik menghubungkan monosakarida, bukan asam amino.",
      B: "Benar, ikatan peptida terbentuk antara gugus karboksil dan gugus amino dua asam amino melalui reaksi kondensasi.",
      C: "Salah, ikatan fosfodiester menghubungkan nukleotida pada asam nukleat.",
      D: "Salah, ikatan hidrogen adalah interaksi lemah yang menstabilkan struktur sekunder protein, bukan ikatan utama antar asam amino.",
      E: "Salah, ikatan disulfida terbentuk antar residu sistein pada struktur tersier, bukan ikatan dasar antar asam amino berurutan.",
    },
  },
  {
    no: 33,
    subject: "Biokimia",
    soal: "Urutan linear asam amino dalam suatu rantai polipeptida disebut struktur protein tingkat...",
    pilihan: {
      A: "Primer",
      B: "Sekunder",
      C: "Tersier",
      D: "Kuarterner",
      E: "Native",
    },
    kunci: "A",
    pembahasan: {
      A: "Benar, struktur primer adalah urutan linear asam amino yang ditentukan oleh kode genetik.",
      B: "Salah, struktur sekunder adalah pola pelipatan lokal seperti alpha helix dan beta sheet.",
      C: "Salah, struktur tersier adalah bentuk lipatan tiga dimensi keseluruhan satu rantai polipeptida.",
      D: "Salah, struktur kuarterner adalah gabungan lebih dari satu rantai polipeptida.",
      E: "Salah, native bukan istilah tingkatan struktur, melainkan istilah untuk bentuk fungsional protein.",
    },
  },
  {
    no: 34,
    subject: "Biokimia",
    soal: "Struktur alpha helix dan beta sheet pada protein yang distabilkan oleh ikatan hidrogen antar tulang punggung polipeptida termasuk struktur protein tingkat...",
    pilihan: {
      A: "Primer",
      B: "Sekunder",
      C: "Tersier",
      D: "Kuarterner",
      E: "Kuinter",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, struktur primer hanya berupa urutan asam amino tanpa pola pelipatan.",
      B: "Benar, alpha helix dan beta sheet adalah pola pelipatan lokal yang menyusun struktur sekunder protein.",
      C: "Salah, struktur tersier adalah pelipatan tiga dimensi keseluruhan rantai, melibatkan interaksi lebih kompleks.",
      D: "Salah, struktur kuarterner melibatkan lebih dari satu rantai polipeptida.",
      E: "Salah, tidak dikenal istilah struktur protein tingkat kuinter.",
    },
  },
  {
    no: 35,
    subject: "Biokimia",
    soal: "Hemoglobin tersusun dari empat rantai polipeptida (2 rantai alfa dan 2 rantai beta) yang saling berikatan. Susunan ini menggambarkan struktur protein tingkat...",
    pilihan: {
      A: "Primer",
      B: "Sekunder",
      C: "Tersier",
      D: "Kuarterner",
      E: "Monomer",
    },
    kunci: "D",
    pembahasan: {
      A: "Salah, struktur primer hanya menggambarkan urutan asam amino satu rantai.",
      B: "Salah, struktur sekunder adalah pola pelipatan lokal satu rantai polipeptida.",
      C: "Salah, struktur tersier adalah lipatan tiga dimensi dari satu rantai tunggal saja.",
      D: "Benar, struktur kuarterner terbentuk dari gabungan lebih dari satu rantai polipeptida, seperti empat rantai pada hemoglobin.",
      E: "Salah, monomer justru merujuk pada satu unit rantai tunggal, berlawanan dengan gabungan pada hemoglobin.",
    },
  },
  {
    no: 36,
    subject: "Biokimia",
    soal: "Molekul yang berfungsi sebagai biokatalisator dengan cara menurunkan energi aktivasi suatu reaksi kimia tanpa ikut bereaksi secara permanen adalah...",
    pilihan: {
      A: "Hormon",
      B: "Enzim",
      C: "Vitamin",
      D: "Koenzim",
      E: "Substrat",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, hormon adalah molekul sinyal untuk mengatur fungsi organ, bukan katalisator reaksi kimia.",
      B: "Benar, enzim adalah biokatalisator yang mempercepat reaksi dengan menurunkan energi aktivasi.",
      C: "Salah, vitamin dapat menjadi prekursor koenzim, tetapi bukan katalisator itu sendiri.",
      D: "Salah, koenzim adalah molekul pembantu enzim, bukan enzim itu sendiri.",
      E: "Salah, substrat adalah molekul yang diubah oleh enzim, bukan katalisatornya.",
    },
  },
  {
    no: 37,
    subject: "Biokimia",
    soal: "Bagian enzim yang secara spesifik berikatan dengan substrat untuk membentuk kompleks enzim-substrat disebut...",
    pilihan: {
      A: "Situs alosterik",
      B: "Sisi aktif (active site)",
      C: "Gugus prostetik",
      D: "Kofaktor",
      E: "Apoenzim",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, situs alosterik adalah tempat pengikatan molekul pengatur, bukan tempat utama pengikatan substrat.",
      B: "Benar, sisi aktif adalah bagian enzim yang berikatan langsung dan spesifik dengan substrat.",
      C: "Salah, gugus prostetik adalah kofaktor non-protein yang terikat kuat pada enzim, bukan tempat pengikatan substrat.",
      D: "Salah, kofaktor adalah molekul tambahan yang membantu aktivitas enzim, bukan tempat pengikatan substrat.",
      E: "Salah, apoenzim adalah bagian protein enzim tanpa kofaktornya, bukan tempat pengikatan substrat.",
    },
  },
  {
    no: 38,
    subject: "Biokimia",
    soal: "Peningkatan suhu yang jauh melebihi suhu optimal enzim akan menyebabkan penurunan aktivitas enzim secara drastis karena terjadi...",
    pilihan: {
      A: "Peningkatan afinitas substrat",
      B: "Denaturasi enzim",
      C: "Aktivasi alosterik",
      D: "Penurunan energi aktivasi",
      E: "Peningkatan konsentrasi substrat",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, suhu ekstrem tidak meningkatkan afinitas, justru merusak struktur pengikatan substrat.",
      B: "Benar, suhu berlebih merusak struktur tiga dimensi enzim (denaturasi) sehingga sisi aktif kehilangan bentuk fungsionalnya.",
      C: "Salah, aktivasi alosterik adalah proses pengaturan normal, bukan efek suhu ekstrem yang merusak.",
      D: "Salah, denaturasi justru meningkatkan hambatan reaksi, bukan menurunkan energi aktivasi.",
      E: "Salah, perubahan suhu tidak mengubah jumlah substrat yang tersedia.",
    },
  },
  {
    no: 39,
    subject: "Biokimia",
    soal: "Trigliserida (lemak netral) tersusun dari satu molekul gliserol yang berikatan dengan...",
    pilihan: {
      A: "Tiga molekul asam amino",
      B: "Tiga molekul asam lemak",
      C: "Tiga molekul monosakarida",
      D: "Satu molekul asam lemak dan fosfat",
      E: "Dua molekul asam lemak",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, asam amino adalah komponen protein, bukan penyusun trigliserida.",
      B: "Benar, trigliserida terbentuk dari satu gliserol yang berikatan ester dengan tiga molekul asam lemak.",
      C: "Salah, monosakarida adalah komponen karbohidrat, bukan lipid.",
      D: "Salah, kombinasi ini menggambarkan struktur fosfolipid, bukan trigliserida.",
      E: "Salah, trigliserida memiliki tiga bukan dua asam lemak yang terikat pada gliserol.",
    },
  },
  {
    no: 40,
    subject: "Biokimia",
    soal: "Asam lemak yang memiliki satu atau lebih ikatan rangkap pada rantai karbonnya disebut asam lemak...",
    pilihan: {
      A: "Jenuh",
      B: "Tak jenuh",
      C: "Trans murni",
      D: "Esensial saja",
      E: "Rantai pendek",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, asam lemak jenuh justru tidak memiliki ikatan rangkap sama sekali pada rantai karbonnya.",
      B: "Benar, asam lemak tak jenuh memiliki satu (monounsaturated) atau lebih (polyunsaturated) ikatan rangkap.",
      C: "Salah, trans hanya merujuk pada konfigurasi geometri ikatan rangkap tertentu, bukan istilah umum untuk semua asam lemak tak jenuh.",
      D: "Salah, esensial merujuk pada asam lemak yang harus diperoleh dari makanan, bukan berdasarkan ada tidaknya ikatan rangkap.",
      E: "Salah, panjang rantai karbon tidak menentukan ada tidaknya ikatan rangkap.",
    },
  },
  {
    no: 41,
    subject: "Biokimia",
    soal: "Fosfolipid pada membran sel memiliki sifat amfipatik, artinya memiliki bagian...",
    pilihan: {
      A: "Hidrofilik seluruhnya",
      B: "Hidrofobik seluruhnya",
      C: "Kepala hidrofilik dan ekor hidrofobik",
      D: "Kepala hidrofobik dan ekor hidrofilik",
      E: "Netral tanpa muatan",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, jika seluruhnya hidrofilik molekul akan larut sempurna dalam air dan tidak dapat membentuk membran.",
      B: "Salah, jika seluruhnya hidrofobik molekul tidak dapat berinteraksi dengan lingkungan berair di kedua sisi membran.",
      C: "Benar, sifat amfipatik fosfolipid berupa kepala fosfat yang hidrofilik dan ekor asam lemak yang hidrofobik, memungkinkan pembentukan bilayer.",
      D: "Salah, susunan ini terbalik dari struktur fosfolipid yang sebenarnya.",
      E: "Salah, fosfolipid justru memiliki bagian bermuatan pada gugus fosfatnya.",
    },
  },
  {
    no: 42,
    subject: "Biokimia",
    soal: "Unit monomer penyusun asam nukleat (DNA/RNA) disebut...",
    pilihan: {
      A: "Asam amino",
      B: "Monosakarida",
      C: "Nukleotida",
      D: "Asam lemak",
      E: "Basa nitrogen saja",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, asam amino adalah monomer protein.",
      B: "Salah, monosakarida adalah monomer karbohidrat, meskipun gula pentosa adalah bagian dari nukleotida.",
      C: "Benar, nukleotida adalah unit monomer lengkap penyusun rantai asam nukleat.",
      D: "Salah, asam lemak adalah komponen lipid, tidak relevan dengan asam nukleat.",
      E: "Salah, basa nitrogen hanya salah satu komponen nukleotida, bukan monomer lengkap.",
    },
  },
  {
    no: 43,
    subject: "Biokimia",
    soal: "Satu nukleotida tersusun atas tiga komponen, yaitu...",
    pilihan: {
      A: "Asam amino, gugus fosfat, dan basa nitrogen",
      B: "Gula pentosa, gugus fosfat, dan basa nitrogen",
      C: "Gula heksosa, asam lemak, dan basa nitrogen",
      D: "Gliserol, asam lemak, dan gugus fosfat",
      E: "Gula pentosa, asam amino, dan gugus fosfat",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, asam amino bukan komponen nukleotida, melainkan komponen protein.",
      B: "Benar, nukleotida tersusun atas gula pentosa (ribosa/deoksiribosa), gugus fosfat, dan basa nitrogen.",
      C: "Salah, gula heksosa dan asam lemak bukan komponen nukleotida.",
      D: "Salah, kombinasi ini menggambarkan komponen fosfolipid, bukan nukleotida.",
      E: "Salah, asam amino tidak termasuk komponen penyusun nukleotida.",
    },
  },
  {
    no: 44,
    subject: "Biokimia",
    soal: "Adenin dan guanin adalah basa nitrogen yang tergolong kelompok...",
    pilihan: {
      A: "Pirimidin",
      B: "Purin",
      C: "Pentosa",
      D: "Fosfat organik",
      E: "Ribonukleosida",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, pirimidin adalah kelompok basa dengan cincin tunggal seperti sitosin, timin, dan urasil.",
      B: "Benar, adenin dan guanin memiliki struktur cincin ganda dan tergolong kelompok basa purin.",
      C: "Salah, pentosa adalah gula penyusun nukleotida, bukan kategori basa nitrogen.",
      D: "Salah, ini bukan istilah pengelompokan basa nitrogen yang dikenal.",
      E: "Salah, ribonukleosida adalah gabungan gula ribosa dengan basa nitrogen, bukan kategori basa itu sendiri.",
    },
  },
  {
    no: 45,
    subject: "Biokimia",
    soal: "Perbedaan utama antara DNA dan RNA meliputi jenis gula dan salah satu jenis basa nitrogennya, yaitu...",
    pilihan: {
      A: "DNA memiliki ribosa, RNA memiliki deoksiribosa; DNA memiliki urasil, RNA memiliki timin",
      B: "DNA memiliki deoksiribosa, RNA memiliki ribosa; DNA memiliki timin, RNA memiliki urasil",
      C: "DNA dan RNA memiliki gula yang sama, hanya berbeda pada basa nitrogennya",
      D: "DNA memiliki deoksiribosa, RNA memiliki ribosa; keduanya sama-sama memiliki timin",
      E: "DNA dan RNA sama persis, tidak ada perbedaan struktural",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, urutan gula dan basa pada pilihan ini tertukar dari yang sebenarnya.",
      B: "Benar, DNA mengandung gula deoksiribosa dan basa timin, sedangkan RNA mengandung gula ribosa dan basa urasil.",
      C: "Salah, DNA dan RNA justru berbeda pada jenis gula pentosanya, bukan hanya pada basa nitrogen.",
      D: "Salah, RNA menggunakan urasil, bukan timin seperti DNA.",
      E: "Salah, DNA dan RNA memiliki beberapa perbedaan struktural mendasar.",
    },
  },
  {
    no: 46,
    subject: "Biokimia",
    soal: "Larutan dengan konsentrasi ion H+ yang sama dengan ion OH- memiliki pH sebesar...",
    pilihan: { A: "0", B: "7", C: "14", D: "1", E: "tidak dapat ditentukan" },
    kunci: "B",
    pembahasan: {
      A: "Salah, pH 0 menggambarkan larutan sangat asam, bukan netral.",
      B: "Benar, pH 7 menunjukkan konsentrasi H+ setara dengan OH-, kondisi ini disebut netral.",
      C: "Salah, pH 14 menggambarkan larutan sangat basa, bukan netral.",
      D: "Salah, pH 1 menggambarkan larutan sangat asam, bukan netral.",
      E: "Salah, pH larutan netral dapat ditentukan secara pasti, yaitu 7 pada suhu standar.",
    },
  },
  {
    no: 47,
    subject: "Biokimia",
    soal: "Larutan yang mampu mempertahankan pH relatif stabil meskipun ditambahkan sedikit asam atau basa disebut larutan...",
    pilihan: {
      A: "Isotonik",
      B: "Buffer (penyangga)",
      C: "Hipertonik",
      D: "Elektrolit kuat",
      E: "Koloid",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, isotonik menggambarkan kesetaraan tekanan osmotik, bukan kestabilan pH.",
      B: "Benar, larutan buffer terdiri atas asam/basa lemah beserta pasangan konjugatnya sehingga mampu mempertahankan pH.",
      C: "Salah, hipertonik menggambarkan tekanan osmotik yang lebih tinggi, tidak berkaitan langsung dengan kestabilan pH.",
      D: "Salah, elektrolit kuat terionisasi sempurna namun tidak selalu mempertahankan pH.",
      E: "Salah, koloid menggambarkan ukuran partikel campuran, tidak berkaitan langsung dengan kestabilan pH.",
    },
  },
  {
    no: 48,
    subject: "Biokimia",
    soal: "Vitamin yang tergolong larut dalam lemak dan cenderung disimpan dalam jaringan adiposa tubuh adalah vitamin...",
    pilihan: {
      A: "B dan C",
      B: "A, D, E, dan K",
      C: "B kompleks saja",
      D: "C saja",
      E: "Semua vitamin larut lemak",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, vitamin B dan C justru tergolong larut air, bukan larut lemak.",
      B: "Benar, vitamin A, D, E, dan K adalah kelompok vitamin larut lemak yang dapat disimpan dalam jaringan adiposa.",
      C: "Salah, vitamin B kompleks tergolong larut air.",
      D: "Salah, vitamin C tergolong larut air, bukan larut lemak.",
      E: "Salah, pernyataan ini tidak spesifik menyebut vitamin mana yang dimaksud.",
    },
  },
  {
    no: 49,
    subject: "Biokimia",
    soal: "Sifat khas enzim yang menyebabkan satu jenis enzim umumnya hanya bekerja pada satu jenis substrat tertentu disebut...",
    pilihan: {
      A: "Reversibilitas",
      B: "Spesifisitas",
      C: "Kooperativitas",
      D: "Inhibisi kompetitif",
      E: "Termolabilitas",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, reversibilitas menggambarkan kemampuan reaksi berjalan dua arah, bukan kekhususan substrat.",
      B: "Benar, spesifisitas enzim merujuk pada kecocokan bentuk sisi aktif dengan substrat tertentu saja.",
      C: "Salah, kooperativitas menggambarkan interaksi antar-subunit protein multimerik seperti hemoglobin, bukan kekhususan substrat enzim.",
      D: "Salah, inhibisi kompetitif adalah salah satu mekanisme penghambatan enzim, bukan sifat kekhususan substrat.",
      E: "Salah, termolabilitas menggambarkan kepekaan enzim terhadap suhu, bukan kekhususan substrat.",
    },
  },
  {
    no: 50,
    subject: "Biokimia",
    soal: "Reaksi kondensasi (dehidrasi) pada pembentukan polimer biologis seperti protein dan karbohidrat selalu disertai pelepasan molekul...",
    pilihan: {
      A: "Karbon dioksida",
      B: "Oksigen",
      C: "Air (H2O)",
      D: "Amonia",
      E: "Glukosa",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, karbon dioksida dilepaskan pada reaksi respirasi seluler, bukan reaksi kondensasi polimer.",
      B: "Salah, oksigen bukan produk sampingan reaksi kondensasi pembentukan polimer.",
      C: "Benar, reaksi kondensasi menggabungkan dua monomer sekaligus melepaskan satu molekul air, misalnya glukosa + fruktosa → sukrosa + H2O.",
      D: "Salah, amonia dilepaskan pada proses deaminasi asam amino, bukan reaksi kondensasi polimer secara umum.",
      E: "Salah, glukosa adalah salah satu monomer yang bereaksi, bukan hasil sampingan reaksi.",
    },
  },

  // ================= FISIOLOGI (51-75) =================
  {
    no: 51,
    subject: "Fisiologi",
    soal: "Kemampuan tubuh mempertahankan lingkungan internal (cairan tubuh, suhu, pH, dll) tetap relatif stabil meskipun terjadi perubahan lingkungan eksternal disebut...",
    pilihan: {
      A: "Metabolisme",
      B: "Homeostasis",
      C: "Adaptasi",
      D: "Termogenesis",
      E: "Osmoregulasi",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, metabolisme adalah keseluruhan reaksi kimia dalam tubuh, bukan istilah kestabilan lingkungan internal.",
      B: "Benar, homeostasis adalah kemampuan tubuh mempertahankan kestabilan lingkungan internal.",
      C: "Salah, adaptasi menggambarkan penyesuaian jangka panjang terhadap lingkungan, bukan mekanisme kestabilan internal sesaat.",
      D: "Salah, termogenesis khusus merujuk pada produksi panas tubuh, bagian kecil dari homeostasis suhu.",
      E: "Salah, osmoregulasi khusus merujuk pada pengaturan keseimbangan air dan elektrolit, bagian kecil dari homeostasis.",
    },
  },
  {
    no: 52,
    subject: "Fisiologi",
    soal: "Mekanisme regulasi tubuh yang bekerja untuk melawan/membalikkan perubahan awal sehingga variabel kembali ke nilai normal disebut umpan balik...",
    pilihan: {
      A: "Positif",
      B: "Negatif",
      C: "Netral",
      D: "Ganda",
      E: "Alosterik",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, umpan balik positif justru memperkuat perubahan awal, bukan melawannya.",
      B: "Benar, umpan balik negatif bekerja melawan perubahan awal untuk mengembalikan variabel ke rentang normal, seperti pada termoregulasi.",
      C: "Salah, tidak dikenal istilah umpan balik netral dalam fisiologi regulasi.",
      D: "Salah, bukan istilah baku untuk mekanisme regulasi ini.",
      E: "Salah, alosterik merujuk pada pengaturan enzim melalui situs pengikatan, bukan mekanisme umpan balik sistemik.",
    },
  },
  {
    no: 53,
    subject: "Fisiologi",
    soal: "Proses persalinan, di mana kontraksi rahim yang semakin kuat justru memicu pelepasan oksitosin lebih banyak sehingga kontraksi makin menguat, adalah contoh mekanisme umpan balik...",
    pilihan: {
      A: "Negatif",
      B: "Positif",
      C: "Homeostatik biasa",
      D: "Alosterik",
      E: "Kompetitif",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, umpan balik negatif akan melemahkan bukan memperkuat rangsangan awal.",
      B: "Benar, umpan balik positif memperkuat perubahan awal secara progresif hingga tercapai suatu titik akhir, seperti pada proses persalinan.",
      C: "Salah, istilah ini tidak spesifik menggambarkan pola penguatan progresif seperti pada kasus ini.",
      D: "Salah, alosterik adalah istilah pengaturan pada tingkat molekul enzim, bukan mekanisme sistemik ini.",
      E: "Salah, kompetitif merujuk pada persaingan pengikatan pada reseptor/enzim, bukan pola umpan balik sistemik.",
    },
  },
  {
    no: 54,
    subject: "Fisiologi",
    soal: "Perpindahan molekul zat terlarut dari daerah berkonsentrasi tinggi ke daerah berkonsentrasi rendah tanpa memerlukan energi disebut...",
    pilihan: {
      A: "Transport aktif primer",
      B: "Difusi sederhana",
      C: "Endositosis",
      D: "Eksositosis",
      E: "Kotransport",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, transport aktif primer memerlukan energi ATP dan dapat melawan gradien konsentrasi.",
      B: "Benar, difusi sederhana adalah perpindahan pasif molekul mengikuti gradien konsentrasi tanpa memerlukan energi.",
      C: "Salah, endositosis adalah proses pemasukan materi ke dalam sel melalui pelekukan membran, memerlukan energi.",
      D: "Salah, eksositosis adalah proses pengeluaran materi dari sel melalui vesikel, memerlukan energi.",
      E: "Salah, kotransport adalah bentuk transport aktif sekunder yang memanfaatkan gradien ion, bukan difusi sederhana.",
    },
  },
  {
    no: 55,
    subject: "Fisiologi",
    soal: "Molekul besar atau bermuatan yang tidak dapat menembus lapisan lipid bilayer secara langsung dapat berdifusi melalui membran dengan bantuan protein channel atau carrier. Proses ini disebut...",
    pilihan: {
      A: "Difusi sederhana",
      B: "Difusi terfasilitasi",
      C: "Transport aktif primer",
      D: "Osmosis",
      E: "Filtrasi",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, difusi sederhana tidak memerlukan bantuan protein membran, hanya untuk molekul kecil/nonpolar.",
      B: "Benar, difusi terfasilitasi memanfaatkan protein carrier atau channel untuk membantu molekul melewati membran mengikuti gradien konsentrasi.",
      C: "Salah, transport aktif primer memerlukan energi ATP dan dapat melawan gradien konsentrasi.",
      D: "Salah, osmosis khusus menggambarkan perpindahan pelarut (air), bukan zat terlarut.",
      E: "Salah, filtrasi adalah perpindahan akibat perbedaan tekanan hidrostatik, bukan gradien konsentrasi melalui protein membran.",
    },
  },
  {
    no: 56,
    subject: "Fisiologi",
    soal: "Perpindahan molekul air melalui membran semipermeabel dari daerah dengan konsentrasi zat terlarut rendah menuju konsentrasi zat terlarut tinggi disebut...",
    pilihan: {
      A: "Difusi sederhana",
      B: "Difusi terfasilitasi",
      C: "Osmosis",
      D: "Transport aktif",
      E: "Endositosis",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, difusi sederhana menggambarkan pergerakan zat terlarut, bukan pelarut air secara spesifik.",
      B: "Salah, difusi terfasilitasi memerlukan bantuan protein membran untuk zat terlarut tertentu.",
      C: "Benar, osmosis adalah perpindahan air melalui membran semipermeabel menuju daerah dengan konsentrasi zat terlarut lebih tinggi.",
      D: "Salah, transport aktif memerlukan energi dan biasanya memindahkan zat terlarut, bukan menggambarkan pergerakan air secara pasif.",
      E: "Salah, endositosis adalah proses pemasukan materi besar ke dalam sel melalui vesikel, bukan pergerakan air melintasi membran.",
    },
  },
  {
    no: 57,
    subject: "Fisiologi",
    soal: "Besarnya tekanan osmotik suatu larutan dapat dihitung menggunakan persamaan van't Hoff: π = MRT. Simbol π pada persamaan tersebut melambangkan...",
    pilihan: {
      A: "Konstanta gas universal",
      B: "Tekanan osmotik",
      C: "Suhu absolut",
      D: "Konsentrasi molar",
      E: "Volume larutan",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, konstanta gas universal dilambangkan dengan R pada persamaan tersebut.",
      B: "Benar, simbol π pada persamaan van't Hoff melambangkan besarnya tekanan osmotik larutan.",
      C: "Salah, suhu absolut dilambangkan dengan T pada persamaan tersebut.",
      D: "Salah, konsentrasi molar dilambangkan dengan M pada persamaan tersebut.",
      E: "Salah, volume larutan tidak dilambangkan secara langsung dalam persamaan ini.",
    },
  },
  {
    no: 58,
    subject: "Fisiologi",
    soal: "Sel darah merah yang dimasukkan ke dalam larutan hipotonik akan mengalami...",
    pilihan: {
      A: "Krenasi (mengerut)",
      B: "Lisis akibat air masuk berlebihan ke dalam sel",
      C: "Tidak mengalami perubahan volume",
      D: "Kehilangan air secara terus-menerus",
      E: "Memadat karena kehilangan air",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, krenasi terjadi pada larutan hipertonik ketika air keluar dari sel, bukan pada larutan hipotonik.",
      B: "Benar, pada larutan hipotonik konsentrasi zat terlarut di luar sel lebih rendah sehingga air masuk ke dalam sel secara osmosis dan dapat menyebabkan sel pecah (lisis).",
      C: "Salah, perubahan volume tetap terjadi karena adanya perbedaan konsentrasi zat terlarut antara larutan hipotonik dan sitoplasma.",
      D: "Salah, air justru masuk, bukan keluar, pada kondisi larutan hipotonik.",
      E: "Salah, sel justru membengkak akibat air yang masuk, bukan memadat.",
    },
  },
  {
    no: 59,
    subject: "Fisiologi",
    soal: "Pompa yang memindahkan 3 ion Na+ keluar sel dan 2 ion K+ masuk sel dengan menggunakan energi dari hidrolisis ATP disebut...",
    pilihan: {
      A: "Kotransporter Na-glukosa",
      B: "Pompa Na-K ATPase",
      C: "Kanal K+ bocor",
      D: "Kanal Na+ berpintu voltase",
      E: "Antiporter Na-Ca",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, kotransporter Na-glukosa adalah bentuk transport aktif sekunder yang tidak langsung menghidrolisis ATP.",
      B: "Benar, pompa Na-K ATPase adalah transport aktif primer yang menghidrolisis ATP untuk memompa 3 Na+ keluar dan 2 K+ masuk sel.",
      C: "Salah, kanal K+ bocor adalah jalur difusi pasif ion kalium, tidak menggunakan energi ATP secara langsung.",
      D: "Salah, kanal Na+ berpintu voltase membuka berdasarkan perubahan voltase membran, bukan pompa yang menghidrolisis ATP.",
      E: "Salah, antiporter Na-Ca adalah bentuk transport aktif sekunder, berbeda mekanisme dengan pompa Na-K ATPase.",
    },
  },
  {
    no: 60,
    subject: "Fisiologi",
    soal: "Nilai potensial membran istirahat pada sebagian besar sel saraf berkisar pada angka mendekati...",
    pilihan: {
      A: "+70 mV",
      B: "0 mV",
      C: "-70 mV",
      D: "-170 mV",
      E: "+170 mV",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, nilai positif ini justru menggambarkan kondisi mendekati puncak potensial aksi, bukan kondisi istirahat.",
      B: "Salah, nilai nol tidak menggambarkan potensial membran istirahat sel saraf yang sebenarnya bermuatan negatif di dalam.",
      C: "Benar, potensial membran istirahat sel saraf berkisar sekitar -70 mV, dengan bagian dalam sel lebih negatif dibanding luar.",
      D: "Salah, nilai ini terlalu negatif dibanding kondisi istirahat sel saraf normal.",
      E: "Salah, nilai ini tidak realistis untuk potensial membran sel saraf.",
    },
  },
  {
    no: 61,
    subject: "Fisiologi",
    soal: "Ion yang paling berperan dalam menentukan besarnya potensial membran istirahat karena permeabilitas membran istirahat yang tinggi terhadapnya adalah ion...",
    pilihan: {
      A: "Natrium (Na+)",
      B: "Kalium (K+)",
      C: "Kalsium (Ca2+)",
      D: "Klorida (Cl-) saja",
      E: "Magnesium (Mg2+)",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, permeabilitas membran istirahat terhadap Na+ relatif rendah dibanding K+.",
      B: "Benar, membran sel saat istirahat jauh lebih permeabel terhadap K+ sehingga pergerakan K+ paling menentukan nilai potensial membran istirahat.",
      C: "Salah, Ca2+ lebih berperan penting saat pelepasan neurotransmitter, bukan penentu utama potensial istirahat.",
      D: "Salah, meskipun Cl- turut berkontribusi, perannya tidak sedominan K+ dalam menentukan potensial istirahat.",
      E: "Salah, Mg2+ bukan penentu utama potensial membran istirahat pada sel saraf.",
    },
  },
  {
    no: 62,
    subject: "Fisiologi",
    soal: "Pusat pengaturan suhu tubuh (termoregulasi) pada sistem saraf pusat terletak di...",
    pilihan: {
      A: "Korteks serebri",
      B: "Hipotalamus",
      C: "Medula oblongata",
      D: "Serebelum",
      E: "Talamus",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, korteks serebri lebih berperan dalam fungsi kognitif dan sensorik yang lebih tinggi, bukan pusat termoregulasi utama.",
      B: "Benar, hipotalamus berfungsi sebagai pusat pengaturan suhu tubuh yang mengintegrasikan sinyal termoreseptor.",
      C: "Salah, medula oblongata lebih berperan dalam pengaturan pernapasan dan kardiovaskular otonom.",
      D: "Salah, serebelum lebih berperan dalam koordinasi gerak dan keseimbangan.",
      E: "Salah, talamus lebih berperan sebagai stasiun relai sensorik, bukan pusat pengaturan suhu.",
    },
  },
  {
    no: 63,
    subject: "Fisiologi",
    soal: "Mekanisme kehilangan panas tubuh melalui perpindahan panas langsung ke benda padat lain yang bersentuhan dengan kulit disebut...",
    pilihan: {
      A: "Radiasi",
      B: "Konduksi",
      C: "Konveksi",
      D: "Evaporasi",
      E: "Sublimasi",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, radiasi adalah kehilangan panas dalam bentuk gelombang elektromagnetik tanpa kontak langsung.",
      B: "Benar, konduksi adalah perpindahan panas melalui kontak langsung antara kulit dan benda padat lain.",
      C: "Salah, konveksi adalah kehilangan panas melalui pergerakan udara atau cairan yang melewati permukaan kulit.",
      D: "Salah, evaporasi adalah kehilangan panas melalui penguapan keringat atau cairan tubuh.",
      E: "Salah, sublimasi bukan mekanisme kehilangan panas tubuh yang relevan secara fisiologis.",
    },
  },
  {
    no: 64,
    subject: "Fisiologi",
    soal: "Saat suhu tubuh meningkat, hipotalamus akan memicu vasodilatasi pembuluh darah kulit dengan tujuan...",
    pilihan: {
      A: "Menahan panas di dalam tubuh",
      B: "Meningkatkan produksi panas metabolik",
      C: "Meningkatkan pelepasan panas ke lingkungan",
      D: "Menurunkan aliran darah ke kulit",
      E: "Memicu menggigil",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, vasodilatasi justru bertujuan melepaskan panas, bukan menahannya di dalam tubuh.",
      B: "Salah, tujuan vasodilatasi bukan meningkatkan produksi panas, melainkan membuang kelebihan panas.",
      C: "Benar, vasodilatasi meningkatkan aliran darah ke kulit sehingga panas lebih banyak dilepaskan ke lingkungan melalui radiasi dan konveksi.",
      D: "Salah, vasodilatasi justru meningkatkan, bukan menurunkan, aliran darah ke kulit.",
      E: "Salah, menggigil adalah respons terhadap suhu tubuh yang menurun, bukan meningkat.",
    },
  },
  {
    no: 65,
    subject: "Fisiologi",
    soal: "Kontraksi otot rangka yang tidak disengaja dan berulang cepat sebagai respons terhadap suhu tubuh yang menurun, bertujuan menghasilkan panas metabolik tambahan, disebut...",
    pilihan: {
      A: "Vasodilatasi",
      B: "Vasokonstriksi",
      C: "Menggigil (shivering)",
      D: "Berkeringat",
      E: "Piloereksi saja",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, vasodilatasi adalah pelebaran pembuluh darah untuk melepas panas, bukan menghasilkan panas melalui kontraksi otot.",
      B: "Salah, vasokonstriksi adalah penyempitan pembuluh darah kulit untuk mengurangi kehilangan panas, bukan kontraksi otot penghasil panas.",
      C: "Benar, menggigil adalah kontraksi otot rangka involunter berulang yang menghasilkan panas metabolik tambahan saat suhu tubuh menurun.",
      D: "Salah, berkeringat justru merupakan mekanisme pelepasan panas, bukan produksi panas.",
      E: "Salah, piloereksi (merinding) membantu isolasi panas namun bukan mekanisme utama penghasil panas metabolik.",
    },
  },
  {
    no: 66,
    subject: "Fisiologi",
    soal: "Rentang pH darah arteri normal pada manusia sehat berada pada kisaran...",
    pilihan: {
      A: "6.35 - 6.45",
      B: "7.00 - 7.10",
      C: "7.35 - 7.45",
      D: "7.80 - 7.90",
      E: "8.00 - 8.10",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, rentang ini terlalu asam dan tidak sesuai kondisi fisiologis normal.",
      B: "Salah, rentang ini sedikit terlalu rendah dari nilai normal darah arteri manusia.",
      C: "Benar, pH darah arteri normal berkisar antara 7.35 hingga 7.45, sedikit basa.",
      D: "Salah, rentang ini terlalu tinggi dan menggambarkan kondisi alkalosis berat yang tidak fisiologis.",
      E: "Salah, rentang ini jauh melebihi batas normal dan tidak sesuai kondisi fisiologis.",
    },
  },
  {
    no: 67,
    subject: "Fisiologi",
    soal: "Sistem buffer yang paling berperan dalam mempertahankan keseimbangan asam-basa darah adalah sistem buffer...",
    pilihan: {
      A: "Fosfat",
      B: "Protein plasma saja",
      C: "Bikarbonat",
      D: "Hemoglobin saja",
      E: "Karbonat anhidrase saja",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, buffer fosfat lebih berperan penting di cairan intraselular dan tubulus ginjal, bukan sistem utama pada darah.",
      B: "Salah, protein plasma berkontribusi namun bukan sistem buffer utama darah.",
      C: "Benar, sistem buffer bikarbonat (H2CO3/HCO3-) adalah sistem buffer utama dan paling dominan dalam mempertahankan pH darah.",
      D: "Salah, hemoglobin berperan sebagai buffer tambahan terutama di dalam eritrosit, bukan sistem utama plasma darah secara keseluruhan.",
      E: "Salah, karbonat anhidrase adalah enzim yang mempercepat reaksi pembentukan bikarbonat, bukan sistem buffer itu sendiri.",
    },
  },
  {
    no: 68,
    subject: "Fisiologi",
    soal: "Kondisi pH darah yang turun di bawah rentang normal (lebih asam dari biasanya) disebut...",
    pilihan: {
      A: "Alkalosis",
      B: "Asidosis",
      C: "Hipoksia",
      D: "Hiperkapnia saja",
      E: "Hipokapnia saja",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, alkalosis justru menggambarkan kondisi pH darah yang meningkat di atas normal.",
      B: "Benar, asidosis adalah kondisi pH darah turun di bawah rentang normal 7.35-7.45, menjadi lebih asam.",
      C: "Salah, hipoksia menggambarkan kekurangan oksigen jaringan, bukan langsung menggambarkan perubahan pH darah.",
      D: "Salah, hiperkapnia menggambarkan peningkatan CO2 darah yang dapat menyebabkan asidosis, namun bukan istilah untuk kondisi pH itu sendiri.",
      E: "Salah, hipokapnia menggambarkan penurunan CO2 darah yang dapat menyebabkan alkalosis, bukan istilah untuk kondisi pH itu sendiri.",
    },
  },
  {
    no: 69,
    subject: "Fisiologi",
    soal: "Peran utama sistem pernapasan dalam menjaga keseimbangan asam-basa adalah dengan mengatur kadar...",
    pilihan: {
      A: "Bikarbonat plasma",
      B: "Karbon dioksida (CO2) darah",
      C: "Ion kalium darah",
      D: "Protein plasma",
      E: "Glukosa darah",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, pengaturan kadar bikarbonat plasma lebih banyak diperankan oleh ginjal, bukan paru-paru.",
      B: "Benar, paru-paru mengatur keseimbangan asam-basa dengan cara mengeluarkan atau menahan CO2 melalui perubahan laju dan kedalaman napas.",
      C: "Salah, pengaturan ion kalium darah lebih banyak diperankan oleh ginjal dan hormon aldosteron, bukan paru-paru.",
      D: "Salah, protein plasma bukan target utama regulasi oleh sistem pernapasan.",
      E: "Salah, glukosa darah diatur oleh hormon insulin dan glukagon, bukan sistem pernapasan.",
    },
  },
  {
    no: 70,
    subject: "Fisiologi",
    soal: "Peran utama ginjal dalam menjaga keseimbangan asam-basa jangka panjang dilakukan melalui...",
    pilihan: {
      A: "Mengatur laju pernapasan",
      B: "Reabsorpsi bikarbonat dan sekresi ion H+",
      C: "Mengatur denyut jantung",
      D: "Produksi hormon insulin",
      E: "Sekresi hormon tiroid",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, pengaturan laju pernapasan adalah fungsi sistem pernapasan, bukan ginjal.",
      B: "Benar, ginjal menjaga keseimbangan asam-basa jangka panjang melalui reabsorpsi bikarbonat serta sekresi ion H+ ke dalam urine.",
      C: "Salah, denyut jantung diatur oleh sistem saraf otonom dan nodus jantung, bukan mekanisme keseimbangan asam-basa ginjal.",
      D: "Salah, produksi insulin dilakukan oleh sel beta pankreas, tidak berkaitan dengan regulasi asam-basa ginjal.",
      E: "Salah, sekresi hormon tiroid dilakukan oleh kelenjar tiroid, tidak berkaitan langsung dengan regulasi asam-basa ginjal.",
    },
  },
  {
    no: 71,
    subject: "Fisiologi",
    soal: "Cairan tubuh total dibagi menjadi dua kompartemen utama, yaitu cairan intraselular dan...",
    pilihan: {
      A: "Cairan interstisial saja",
      B: "Cairan ekstraselular",
      C: "Cairan limfatik saja",
      D: "Plasma darah saja",
      E: "Cairan transelular saja",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, cairan interstisial hanyalah salah satu bagian dari cairan ekstraselular, bukan kompartemen utama yang sejajar dengan cairan intraselular.",
      B: "Benar, cairan tubuh total terbagi menjadi cairan intraselular (di dalam sel) dan cairan ekstraselular (di luar sel).",
      C: "Salah, cairan limfatik hanya salah satu bagian kecil dari cairan ekstraselular.",
      D: "Salah, plasma darah hanya salah satu komponen dari cairan ekstraselular.",
      E: "Salah, cairan transelular hanya salah satu bagian kecil dan khusus dari cairan ekstraselular.",
    },
  },
  {
    no: 72,
    subject: "Fisiologi",
    soal: "Cairan ekstraselular terutama terdiri atas dua komponen besar, yaitu plasma darah dan...",
    pilihan: {
      A: "Cairan intraselular",
      B: "Cairan interstisial",
      C: "Sitosol",
      D: "Cairan intrasitoplasma",
      E: "Cairan nukleoplasma",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, cairan intraselular justru berada di dalam sel, terpisah dari cairan ekstraselular.",
      B: "Benar, cairan ekstraselular terutama terdiri atas plasma darah (di dalam pembuluh darah) dan cairan interstisial (di sela-sela jaringan).",
      C: "Salah, sitosol adalah cairan di dalam sel, bagian dari cairan intraselular.",
      D: "Salah, bukan istilah baku dalam pembagian kompartemen cairan tubuh.",
      E: "Salah, cairan nukleoplasma berada di dalam inti sel, bagian dari cairan intraselular.",
    },
  },
  {
    no: 73,
    subject: "Fisiologi",
    soal: "Persentase air terhadap berat badan total pada orang dewasa sehat rata-rata berkisar sekitar...",
    pilihan: { A: "20%", B: "40%", C: "60%", D: "80%", E: "95%" },
    kunci: "C",
    pembahasan: {
      A: "Salah, persentase ini terlalu rendah dibanding kadar air tubuh rata-rata orang dewasa.",
      B: "Salah, meskipun mendekati, angka ini masih di bawah rata-rata umum yang digunakan sebagai acuan fisiologi.",
      C: "Benar, air tubuh total pada orang dewasa rata-rata sekitar 60% dari berat badan, walau dapat bervariasi menurut usia, jenis kelamin, dan komposisi tubuh.",
      D: "Salah, persentase ini terlalu tinggi dibanding kadar air tubuh rata-rata orang dewasa.",
      E: "Salah, persentase ini jauh melebihi kadar air tubuh manusia dewasa yang realistis.",
    },
  },
  {
    no: 74,
    subject: "Fisiologi",
    soal: "Ion yang menjadi kation utama pada cairan ekstraselular adalah...",
    pilihan: {
      A: "Kalium (K+)",
      B: "Natrium (Na+)",
      C: "Kalsium (Ca2+) saja",
      D: "Magnesium (Mg2+) saja",
      E: "Fosfat",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, kalium justru merupakan kation utama pada cairan intraselular, bukan ekstraselular.",
      B: "Benar, natrium adalah kation utama pada cairan ekstraselular yang berperan penting dalam menjaga tekanan osmotik cairan tubuh.",
      C: "Salah, kalsium hadir dalam jumlah lebih kecil dibanding natrium pada cairan ekstraselular.",
      D: "Salah, magnesium bukan kation utama pada cairan ekstraselular, konsentrasinya lebih tinggi di intraselular.",
      E: "Salah, fosfat adalah anion, bukan kation, dan lebih banyak terdapat di cairan intraselular.",
    },
  },
  {
    no: 75,
    subject: "Fisiologi",
    soal: "Ion yang menjadi kation utama pada cairan intraselular adalah...",
    pilihan: {
      A: "Natrium (Na+)",
      B: "Klorida (Cl-)",
      C: "Kalium (K+)",
      D: "Kalsium (Ca2+)",
      E: "Bikarbonat (HCO3-)",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, natrium justru merupakan kation utama pada cairan ekstraselular, bukan intraselular.",
      B: "Salah, klorida adalah anion, bukan kation, dan lebih dominan di cairan ekstraselular.",
      C: "Benar, kalium adalah kation utama pada cairan intraselular dengan konsentrasi jauh lebih tinggi di dalam sel dibanding luar sel.",
      D: "Salah, kalsium bebas intraselular justru dijaga sangat rendah dibanding konsentrasi ekstraselularnya.",
      E: "Salah, bikarbonat adalah anion, bukan kation, dan lebih dominan di cairan ekstraselular.",
    },
  },

  // ================= HISTOLOGI (76-100) =================
  {
    no: 76,
    subject: "Histologi",
    soal: "Empat jaringan dasar penyusun tubuh manusia adalah jaringan epitel, jaringan ikat, jaringan otot, dan jaringan...",
    pilihan: {
      A: "Darah",
      B: "Saraf",
      C: "Lemak",
      D: "Tulang",
      E: "Kartilago",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, darah tergolong jenis khusus jaringan ikat, bukan jaringan dasar tersendiri.",
      B: "Benar, empat jaringan dasar tubuh adalah epitel, ikat, otot, dan saraf.",
      C: "Salah, jaringan lemak (adiposa) tergolong jenis jaringan ikat, bukan jaringan dasar tersendiri.",
      D: "Salah, tulang tergolong jenis jaringan ikat khusus, bukan jaringan dasar tersendiri.",
      E: "Salah, kartilago tergolong jenis jaringan ikat khusus, bukan jaringan dasar tersendiri.",
    },
  },
  {
    no: 77,
    subject: "Histologi",
    soal: "Jaringan yang melapisi permukaan tubuh, melapisi rongga organ dalam, dan membentuk sebagian besar kelenjar, dengan fungsi utama proteksi, absorpsi, dan sekresi, adalah jaringan...",
    pilihan: { A: "Ikat", B: "Epitel", C: "Otot", D: "Saraf", E: "Adiposa" },
    kunci: "B",
    pembahasan: {
      A: "Salah, jaringan ikat berfungsi menyokong dan menghubungkan jaringan lain, bukan melapisi permukaan sebagai fungsi utamanya.",
      B: "Benar, jaringan epitel melapisi permukaan tubuh dan rongga organ serta membentuk kelenjar, dengan fungsi proteksi, absorpsi, dan sekresi.",
      C: "Salah, jaringan otot berfungsi menghasilkan gerakan melalui kontraksi, bukan melapisi permukaan.",
      D: "Salah, jaringan saraf berfungsi menghantarkan impuls listrik, bukan melapisi permukaan tubuh.",
      E: "Salah, jaringan adiposa adalah jenis jaringan ikat penyimpan lemak, bukan jaringan pelapis permukaan.",
    },
  },
  {
    no: 78,
    subject: "Histologi",
    soal: "Epitel yang tersusun dari satu lapis sel pipih dan ditemukan pada dinding alveolus paru serta endotel pembuluh darah disebut...",
    pilihan: {
      A: "Epitel kuboid simpleks",
      B: "Epitel skuamosa simpleks",
      C: "Epitel kolumnar simpleks",
      D: "Epitel skuamosa berlapis",
      E: "Epitel transisional",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, epitel kuboid simpleks tersusun dari sel berbentuk kubus, bukan pipih, dan biasa ditemukan pada tubulus ginjal.",
      B: "Benar, epitel skuamosa simpleks tersusun dari satu lapis sel pipih, sesuai dengan struktur alveolus dan endotel pembuluh darah yang memudahkan pertukaran zat.",
      C: "Salah, epitel kolumnar simpleks tersusun dari sel berbentuk silindris tinggi, bukan pipih.",
      D: "Salah, epitel skuamosa berlapis tersusun dari banyak lapisan sel, tidak sesuai dengan struktur tipis alveolus.",
      E: "Salah, epitel transisional ditemukan pada saluran kemih, bukan pada alveolus atau pembuluh darah.",
    },
  },
  {
    no: 79,
    subject: "Histologi",
    soal: "Epitel kolumnar bersilia yang berfungsi menyapu partikel/mukus ke arah tertentu banyak ditemukan pada...",
    pilihan: {
      A: "Epidermis kulit",
      B: "Saluran pernapasan (trakea)",
      C: "Alveolus paru",
      D: "Ginjal",
      E: "Esofagus",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, epidermis kulit tersusun dari epitel skuamosa berlapis, bukan epitel kolumnar bersilia.",
      B: "Benar, epitel kolumnar bersilia banyak ditemukan pada saluran pernapasan seperti trakea untuk menyapu mukus dan partikel asing keluar.",
      C: "Salah, alveolus paru dilapisi epitel skuamosa simpleks yang tipis untuk pertukaran gas, bukan epitel bersilia.",
      D: "Salah, sebagian besar tubulus ginjal dilapisi epitel kuboid, bukan epitel kolumnar bersilia.",
      E: "Salah, esofagus dilapisi epitel skuamosa berlapis, bukan epitel kolumnar bersilia.",
    },
  },
  {
    no: 80,
    subject: "Histologi",
    soal: "Epitel transisional yang dapat berubah bentuk (dari kuboid menjadi pipih) untuk menyesuaikan derajat peregangan organ, banyak ditemukan pada...",
    pilihan: {
      A: "Vesika urinaria (kandung kemih)",
      B: "Lambung",
      C: "Usus halus",
      D: "Trakea",
      E: "Kelenjar tiroid",
    },
    kunci: "A",
    pembahasan: {
      A: "Benar, epitel transisional khas ditemukan pada vesika urinaria dan saluran kemih karena mampu meregang saat organ terisi penuh.",
      B: "Salah, lambung dilapisi epitel kolumnar simpleks yang berfungsi sekresi, bukan epitel transisional.",
      C: "Salah, usus halus dilapisi epitel kolumnar simpleks dengan mikrovili untuk absorpsi, bukan epitel transisional.",
      D: "Salah, trakea dilapisi epitel kolumnar bersilia semu berlapis, bukan epitel transisional.",
      E: "Salah, kelenjar tiroid tersusun dari epitel folikular kuboid, bukan epitel transisional.",
    },
  },
  {
    no: 81,
    subject: "Histologi",
    soal: "Kelenjar yang menyalurkan hasil sekresinya melalui saluran (duktus) langsung ke permukaan epitel atau organ tertentu disebut kelenjar...",
    pilihan: {
      A: "Endokrin",
      B: "Eksokrin",
      C: "Campuran saja",
      D: "Autokrin",
      E: "Parakrin",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, kelenjar endokrin menyalurkan hasil sekresinya langsung ke pembuluh darah tanpa saluran/duktus.",
      B: "Benar, kelenjar eksokrin memiliki saluran (duktus) yang mengalirkan sekretnya ke permukaan epitel atau rongga organ.",
      C: "Salah, campuran menggambarkan organ dengan kedua sifat, bukan definisi umum kelenjar dengan saluran duktus.",
      D: "Salah, autokrin adalah istilah mekanisme sinyal sel terhadap dirinya sendiri, bukan jenis kelenjar.",
      E: "Salah, parakrin adalah istilah mekanisme sinyal sel terhadap sel tetangga, bukan jenis kelenjar.",
    },
  },
  {
    no: 82,
    subject: "Histologi",
    soal: "Kelenjar yang menyalurkan hasil sekresinya (hormon) langsung ke dalam pembuluh darah tanpa melalui saluran disebut kelenjar...",
    pilihan: {
      A: "Eksokrin",
      B: "Endokrin",
      C: "Sebasea",
      D: "Sudorifera",
      E: "Merokrin",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, kelenjar eksokrin justru menggunakan saluran (duktus) untuk menyalurkan sekretnya.",
      B: "Benar, kelenjar endokrin melepaskan hormonnya langsung ke aliran darah tanpa saluran khusus.",
      C: "Salah, kelenjar sebasea adalah salah satu contoh kelenjar eksokrin pada kulit, bukan kelenjar endokrin.",
      D: "Salah, kelenjar sudorifera (kelenjar keringat) adalah kelenjar eksokrin, bukan endokrin.",
      E: "Salah, merokrin adalah salah satu cara sekresi kelenjar eksokrin, bukan jenis kelenjar endokrin.",
    },
  },
  {
    no: 83,
    subject: "Histologi",
    soal: "Komponen utama penyusun jaringan ikat meliputi sel, serat, dan...",
    pilihan: {
      A: "Matriks ekstraselular",
      B: "Membran basalis saja",
      C: "Silia",
      D: "Mikrovili",
      E: "Desmosom",
    },
    kunci: "A",
    pembahasan: {
      A: "Benar, jaringan ikat tersusun atas sel, serat (kolagen, elastin, retikulin), dan matriks ekstraselular (substansi dasar) yang mengisi ruang antar sel.",
      B: "Salah, membran basalis adalah struktur pemisah epitel dengan jaringan ikat di bawahnya, bukan komponen utama penyusun jaringan ikat.",
      C: "Salah, silia adalah struktur permukaan sel epitel, tidak berkaitan dengan komponen jaringan ikat.",
      D: "Salah, mikrovili adalah struktur permukaan sel epitel untuk memperluas area absorpsi, bukan komponen jaringan ikat.",
      E: "Salah, desmosom adalah struktur perlekatan antar sel epitel, bukan komponen jaringan ikat.",
    },
  },
  {
    no: 84,
    subject: "Histologi",
    soal: "Serat jaringan ikat yang memberikan kekuatan tarik tinggi (tensile strength) dan merupakan protein paling banyak dalam tubuh adalah serat...",
    pilihan: {
      A: "Elastin",
      B: "Retikulin",
      C: "Kolagen",
      D: "Aktin",
      E: "Miosin",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, elastin memberikan sifat elastisitas/kelenturan, bukan kekuatan tarik tinggi seperti kolagen.",
      B: "Salah, retikulin membentuk kerangka halus penyokong organ lunak, jumlahnya jauh lebih sedikit dibanding kolagen.",
      C: "Benar, kolagen adalah protein struktural paling banyak dalam tubuh dan memberikan kekuatan tarik tinggi pada jaringan ikat.",
      D: "Salah, aktin adalah protein kontraktil pada sel otot, bukan serat jaringan ikat.",
      E: "Salah, miosin adalah protein kontraktil pada sel otot, bukan serat jaringan ikat.",
    },
  },
  {
    no: 85,
    subject: "Histologi",
    soal: "Serat jaringan ikat yang memungkinkan jaringan meregang lalu kembali ke bentuk semula, banyak ditemukan pada dinding pembuluh darah besar dan ligamen tertentu, adalah serat...",
    pilihan: {
      A: "Kolagen",
      B: "Elastin",
      C: "Retikulin",
      D: "Fibronektin",
      E: "Laminin",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, kolagen memberikan kekuatan tarik namun kurang elastis dibanding elastin.",
      B: "Benar, serat elastin memiliki kemampuan meregang dan kembali ke bentuk semula, sesuai fungsinya pada dinding arteri besar dan ligamen elastis.",
      C: "Salah, retikulin membentuk jalinan halus penyokong, tidak seelastis elastin.",
      D: "Salah, fibronektin adalah protein perekat matriks ekstraselular, bukan serat elastis.",
      E: "Salah, laminin adalah protein pada membran basalis, bukan serat elastis jaringan ikat.",
    },
  },
  {
    no: 86,
    subject: "Histologi",
    soal: "Jaringan ikat yang tersusun longgar dengan banyak substansi dasar dan sedikit serat, berfungsi sebagai bantalan serta tempat lewatnya pembuluh darah dan saraf menuju organ, disebut jaringan ikat...",
    pilihan: {
      A: "Padat teratur",
      B: "Padat tak teratur",
      C: "Longgar (areolar)",
      D: "Tulang rawan hialin",
      E: "Tulang kompak",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, jaringan ikat padat teratur memiliki serat kolagen tersusun rapi dan padat, seperti pada tendon.",
      B: "Salah, jaringan ikat padat tak teratur memiliki serat kolagen padat namun tidak beraturan, seperti pada dermis kulit.",
      C: "Benar, jaringan ikat longgar (areolar) memiliki susunan serat yang jarang dan banyak substansi dasar, berfungsi sebagai bantalan dan jalur pembuluh darah/saraf.",
      D: "Salah, tulang rawan hialin memiliki matriks kaku dan bening, berbeda dari jaringan ikat longgar.",
      E: "Salah, tulang kompak adalah jaringan ikat terkalsifikasi yang keras, sangat berbeda dari jaringan ikat longgar.",
    },
  },
  {
    no: 87,
    subject: "Histologi",
    soal: "Jaringan ikat khusus yang tersusun dari sel-sel penyimpan lemak (adiposit) dan berfungsi sebagai cadangan energi serta bantalan/isolasi, disebut jaringan...",
    pilihan: {
      A: "Adiposa",
      B: "Retikuler",
      C: "Mukosa",
      D: "Kartilago elastis",
      E: "Hemopoietik",
    },
    kunci: "A",
    pembahasan: {
      A: "Benar, jaringan adiposa tersusun dari sel adiposit yang menyimpan lemak sebagai cadangan energi serta berfungsi sebagai bantalan dan isolasi panas.",
      B: "Salah, jaringan retikuler tersusun dari serat retikulin halus, membentuk kerangka organ limfoid, bukan penyimpan lemak.",
      C: "Salah, jaringan mukosa (jelly Wharton) adalah jaringan ikat embrional pada tali pusat, bukan penyimpan lemak dewasa.",
      D: "Salah, kartilago elastis adalah jenis tulang rawan dengan serat elastin, bukan jaringan penyimpan lemak.",
      E: "Salah, jaringan hemopoietik berfungsi memproduksi sel darah, bukan menyimpan lemak.",
    },
  },
  {
    no: 88,
    subject: "Histologi",
    soal: "Jenis tulang rawan yang paling banyak ditemukan di tubuh, bersifat translusen, dan menyusun permukaan sendi serta cincin trakea, adalah kartilago...",
    pilihan: {
      A: "Elastis",
      B: "Fibrosa",
      C: "Hialin",
      D: "Kompak",
      E: "Spons",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, kartilago elastis banyak mengandung serat elastin dan ditemukan pada daun telinga serta epiglotis, bukan permukaan sendi.",
      B: "Salah, kartilago fibrosa memiliki banyak serat kolagen kasar dan ditemukan pada diskus intervertebralis, bukan jenis paling umum di tubuh.",
      C: "Benar, kartilago hialin adalah jenis tulang rawan paling umum, bersifat translusen, dan menyusun permukaan sendi serta cincin trakea.",
      D: "Salah, kompak dan spons adalah istilah klasifikasi jaringan tulang keras, bukan tulang rawan.",
      E: "Salah, sama seperti D, spons adalah istilah untuk tulang keras, bukan tulang rawan.",
    },
  },
  {
    no: 89,
    subject: "Histologi",
    soal: "Unit struktural dasar pada tulang kompak (kortikal) yang terdiri atas lamela konsentris mengelilingi kanal pusat berisi pembuluh darah disebut...",
    pilihan: {
      A: "Osteon (sistem Havers)",
      B: "Kondrosit",
      C: "Lakuna saja",
      D: "Trabekula",
      E: "Periosteum",
    },
    kunci: "A",
    pembahasan: {
      A: "Benar, osteon (sistem Havers) adalah unit struktural dasar tulang kompak, terdiri atas lamela konsentris mengelilingi kanal Havers yang berisi pembuluh darah.",
      B: "Salah, kondrosit adalah sel penyusun tulang rawan, bukan unit struktural tulang keras.",
      C: "Salah, lakuna hanyalah rongga kecil tempat osteosit berada, bukan keseluruhan unit struktural.",
      D: "Salah, trabekula adalah struktur penyusun tulang spons, bukan tulang kompak.",
      E: "Salah, periosteum adalah selaput pembungkus permukaan luar tulang, bukan unit struktural internal.",
    },
  },
  {
    no: 90,
    subject: "Histologi",
    soal: "Sel tulang yang berfungsi membentuk matriks tulang baru (osteoid) dan aktif mensintesis kolagen tipe I disebut...",
    pilihan: {
      A: "Osteosit",
      B: "Osteoblas",
      C: "Osteoklas",
      D: "Kondroblas",
      E: "Fibroblas",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, osteosit adalah sel tulang dewasa yang terperangkap dalam lakuna dan berfungsi mempertahankan matriks, bukan membentuk matriks baru secara aktif.",
      B: "Benar, osteoblas adalah sel yang aktif mensintesis dan mensekresikan matriks tulang baru (osteoid) yang kaya kolagen tipe I.",
      C: "Salah, osteoklas justru berfungsi menyerap/merombak matriks tulang, kebalikan dari fungsi pembentukan.",
      D: "Salah, kondroblas berfungsi membentuk matriks tulang rawan, bukan matriks tulang keras.",
      E: "Salah, fibroblas berfungsi membentuk serat dan matriks jaringan ikat biasa, bukan matriks tulang secara khusus.",
    },
  },
  {
    no: 91,
    subject: "Histologi",
    soal: "Darah dapat digolongkan sebagai jaringan ikat khusus karena memiliki matriks ekstraselular berupa cairan, yaitu...",
    pilihan: {
      A: "Serum",
      B: "Plasma",
      C: "Limfe",
      D: "Cairan interstisial",
      E: "Cairan sinovial",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, serum adalah plasma yang telah kehilangan faktor pembekuan (fibrinogen), bukan istilah matriks darah secara utuh.",
      B: "Benar, darah digolongkan jaringan ikat khusus karena sel-sel darah (eritrosit, leukosit, trombosit) terendam dalam matriks cair yaitu plasma.",
      C: "Salah, limfe adalah cairan pada sistem limfatik, bukan matriks darah.",
      D: "Salah, cairan interstisial adalah cairan di sela-sela jaringan, bukan matriks darah.",
      E: "Salah, cairan sinovial adalah cairan pelumas sendi, bukan matriks darah.",
    },
  },
  {
    no: 92,
    subject: "Histologi",
    soal: "Ciri khas jaringan otot rangka yang membedakannya dari jenis otot lain adalah memiliki gambaran lurik dengan inti sel...",
    pilihan: {
      A: "Tunggal terletak di tengah",
      B: "Banyak terletak di tepi sel",
      C: "Tunggal terletak di tepi sel",
      D: "Tidak memiliki inti sel",
      E: "Banyak terletak di tengah sel",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, ciri ini justru menggambarkan otot polos, bukan otot rangka.",
      B: "Benar, otot rangka memiliki banyak inti (multinuklei) yang terletak di tepi (perifer) sel akibat proses fusi banyak sel mioblas saat perkembangan.",
      C: "Salah, otot rangka memiliki banyak inti, bukan hanya satu.",
      D: "Salah, otot rangka tetap memiliki inti sel, hanya letaknya di tepi dan jumlahnya banyak.",
      E: "Salah, meskipun berinti banyak, letak intinya berada di tepi bukan di tengah sel otot rangka.",
    },
  },
  {
    no: 93,
    subject: "Histologi",
    soal: "Jaringan otot yang tidak menunjukkan gambaran lurik, berinti tunggal di tengah sel berbentuk gelendong, dan bekerja secara involunter, banyak ditemukan pada dinding organ visera seperti usus dan pembuluh darah, adalah otot...",
    pilihan: {
      A: "Rangka",
      B: "Polos",
      C: "Jantung",
      D: "Lurik volunter",
      E: "Skelet",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, otot rangka menunjukkan gambaran lurik dan bekerja volunter, tidak sesuai deskripsi.",
      B: "Benar, otot polos tidak bergambaran lurik, berinti tunggal di tengah sel gelendong, dan bekerja involunter pada organ visera.",
      C: "Salah, otot jantung menunjukkan gambaran lurik dan memiliki diskus interkalaris, berbeda dari deskripsi otot polos.",
      D: "Salah, istilah ini menggambarkan otot rangka, bukan otot polos.",
      E: "Salah, skelet adalah istilah lain untuk otot rangka, bukan otot polos.",
    },
  },
  {
    no: 94,
    subject: "Histologi",
    soal: "Struktur khas yang hanya ditemukan pada jaringan otot jantung, berupa taut khusus antar sel yang memungkinkan penghantaran impuls listrik dengan cepat antar kardiomiosit, disebut...",
    pilihan: {
      A: "Diskus interkalaris",
      B: "Tubulus T saja",
      C: "Sarkomer",
      D: "Miofibril",
      E: "Sarkolema",
    },
    kunci: "A",
    pembahasan: {
      A: "Benar, diskus interkalaris adalah taut khusus antar sel otot jantung yang mengandung gap junction untuk penghantaran impuls listrik cepat antar kardiomiosit.",
      B: "Salah, tubulus T ditemukan pada otot rangka maupun jantung namun bukan struktur khas penghubung antar sel yang unik pada otot jantung.",
      C: "Salah, sarkomer adalah unit kontraktil dasar otot lurik secara umum, ditemukan juga pada otot rangka, bukan struktur khas penghubung sel jantung.",
      D: "Salah, miofibril adalah struktur kontraktil di dalam sel otot, ditemukan pada otot rangka dan jantung, bukan struktur penghubung antar sel.",
      E: "Salah, sarkolema adalah membran sel otot secara umum, bukan struktur penghubung khusus antar sel jantung.",
    },
  },
  {
    no: 95,
    subject: "Histologi",
    soal: "Unit fungsional dasar pada jaringan saraf yang bertanggung jawab menghantarkan impuls listrik disebut...",
    pilihan: {
      A: "Neuroglia",
      B: "Neuron",
      C: "Sinaps saja",
      D: "Mielin",
      E: "Nodus Ranvier",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, neuroglia adalah sel pendukung yang tidak menghantarkan impuls secara langsung seperti neuron.",
      B: "Benar, neuron adalah unit fungsional dasar jaringan saraf yang bertanggung jawab menerima dan menghantarkan impuls listrik.",
      C: "Salah, sinaps adalah titik pertemuan antar neuron untuk transmisi sinyal, bukan unit fungsional dasar itu sendiri.",
      D: "Salah, mielin adalah selubung lemak pembungkus akson yang mempercepat konduksi, bukan unit fungsional dasar.",
      E: "Salah, nodus Ranvier adalah celah pada selubung mielin, bukan unit fungsional dasar jaringan saraf.",
    },
  },
  {
    no: 96,
    subject: "Histologi",
    soal: "Bagian neuron yang berfungsi menerima rangsangan dari neuron lain dan menghantarkannya menuju badan sel disebut...",
    pilihan: {
      A: "Akson",
      B: "Dendrit",
      C: "Nodus Ranvier",
      D: "Selubung mielin",
      E: "Terminal akson",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, akson berfungsi menghantarkan impuls menjauhi badan sel menuju neuron/sel target lain, bukan menerima rangsangan awal.",
      B: "Benar, dendrit adalah bagian neuron yang menerima rangsangan dari neuron lain dan menghantarkannya menuju badan sel.",
      C: "Salah, nodus Ranvier adalah celah pada selubung mielin sepanjang akson, bukan bagian penerima rangsangan.",
      D: "Salah, selubung mielin berfungsi mengisolasi dan mempercepat konduksi impuls sepanjang akson, bukan menerima rangsangan.",
      E: "Salah, terminal akson adalah ujung akson tempat pelepasan neurotransmitter, bukan bagian penerima rangsangan awal.",
    },
  },
  {
    no: 97,
    subject: "Histologi",
    soal: "Sel-sel pendukung pada jaringan saraf yang berfungsi memberi nutrisi, perlindungan, dan membentuk selubung mielin, namun tidak menghantarkan impuls saraf secara langsung, disebut sel...",
    pilihan: {
      A: "Neuron motorik",
      B: "Neuroglia (sel glia)",
      C: "Neuron sensorik",
      D: "Interneuron",
      E: "Neuron bipolar",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, neuron motorik justru menghantarkan impuls dari sistem saraf pusat menuju otot/kelenjar efektor.",
      B: "Benar, sel neuroglia berfungsi mendukung, memberi nutrisi, dan sebagian membentuk selubung mielin bagi neuron, tanpa menghantarkan impuls secara langsung.",
      C: "Salah, neuron sensorik menghantarkan impuls dari reseptor menuju sistem saraf pusat, bukan sekadar sel pendukung.",
      D: "Salah, interneuron adalah neuron penghubung di dalam sistem saraf pusat, tetap menghantarkan impuls.",
      E: "Salah, neuron bipolar adalah salah satu klasifikasi bentuk neuron berdasarkan jumlah juluran, tetap menghantarkan impuls.",
    },
  },
  {
    no: 98,
    subject: "Histologi",
    soal: "Selubung mielin pada akson neuron di sistem saraf tepi (perifer) dibentuk oleh sel...",
    pilihan: {
      A: "Oligodendrosit",
      B: "Sel Schwann",
      C: "Astrosit",
      D: "Mikroglia",
      E: "Sel ependima",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, oligodendrosit membentuk selubung mielin pada sistem saraf pusat, bukan sistem saraf tepi.",
      B: "Benar, sel Schwann adalah sel glia yang membentuk selubung mielin pada akson neuron di sistem saraf tepi.",
      C: "Salah, astrosit berfungsi mendukung sawar darah otak dan homeostasis lingkungan neuron di sistem saraf pusat, bukan membentuk mielin.",
      D: "Salah, mikroglia berfungsi sebagai sel imun/fagosit pada sistem saraf pusat, bukan membentuk mielin.",
      E: "Salah, sel ependima melapisi rongga ventrikel otak dan kanalis sentralis, bukan membentuk mielin.",
    },
  },
  {
    no: 99,
    subject: "Histologi",
    soal: "Pada teknik pewarnaan Hematoksilin-Eosin (H&E) yang umum digunakan dalam preparat histologi, hematoksilin bersifat basa dan akan mewarnai struktur yang bersifat asam (seperti inti sel) menjadi warna...",
    pilihan: {
      A: "Merah muda (eosinofilik)",
      B: "Ungu kebiruan (basofilik)",
      C: "Kuning",
      D: "Hijau",
      E: "Tidak berwarna",
    },
    kunci: "B",
    pembahasan: {
      A: "Salah, warna merah muda dihasilkan oleh pewarnaan eosin yang bersifat asam pada struktur sitoplasma yang bersifat basa.",
      B: "Benar, hematoksilin yang bersifat basa akan berikatan dengan struktur asam seperti asam nukleat pada inti sel, menghasilkan warna ungu kebiruan (basofilik).",
      C: "Salah, warna kuning bukan hasil khas pewarnaan H&E standar.",
      D: "Salah, warna hijau bukan hasil khas pewarnaan H&E standar.",
      E: "Salah, inti sel justru akan tampak jelas berwarna setelah pewarnaan hematoksilin, bukan tidak berwarna.",
    },
  },
  {
    no: 100,
    subject: "Histologi",
    soal: "Mikroskop yang paling umum digunakan pada praktikum histologi dasar untuk mengamati preparat jaringan yang telah diwarnai adalah mikroskop...",
    pilihan: {
      A: "Elektron transmisi",
      B: "Elektron scanning",
      C: "Cahaya (light microscope)",
      D: "Fluoresensi saja",
      E: "Confocal saja",
    },
    kunci: "C",
    pembahasan: {
      A: "Salah, mikroskop elektron transmisi digunakan untuk pengamatan struktur ultra-halus sel, bukan praktikum histologi dasar rutin.",
      B: "Salah, mikroskop elektron scanning digunakan untuk mengamati permukaan struktur secara tiga dimensi pada resolusi sangat tinggi, bukan praktikum dasar.",
      C: "Benar, mikroskop cahaya adalah alat yang paling umum dan mendasar digunakan dalam praktikum histologi untuk mengamati preparat jaringan berwarna.",
      D: "Salah, mikroskop fluoresensi digunakan untuk teknik pewarnaan khusus tertentu, bukan alat dasar praktikum histologi rutin.",
      E: "Salah, mikroskop confocal digunakan untuk pencitraan tingkat lanjut, bukan alat dasar praktikum histologi rutin.",
    },
  },
];
